@host = http://localhost:3000/api

GET {{host}}/experience

###

GET {{host}}/experience/1

###
POST {{host}}/experience
Content-Type: application/json

{
  
  "title": "Senior Sales Representative",
  "company": "Abbott",
  "startDate": "2022-01-01",
  "finishDate": "Actualmente",
  "contract": "Indefinido",
  "description": "Representante de ventas zona norte y técnico de
quirófano en neuromodulation medical devices para el Párkinson y dolor crónico.",
  "tools": [
    "Quirófano",
    "Ventas",
    "Dolor crónico",
    "Párkinson",
    "Formador",
    "Licitaciones",
    "negociación",
    "medical devices"
  ]
}

###
POST {{host}}/experience
Content-Type: application/json

{
  
  "title": "Senior Sales Representative",
  "company": "Prim",
  "startDate": "2020-02-01",
  "finishDate": "2021-11-30",
  "contract": "Indefinido",
  "description": "Jefe de producto y representante de ventas zona norte y técnico de
quirófano en neuromodulation medical devices para el Párkinson y dolor crónico.",
  "tools": [
    "Quirófano",
    "Ventas",
    "Dolor crónico",
    "Párkinson",
    "Formador",
    "Licitaciones",
    "negociación",
    "medical devices",
    "Gestión de equipos",
    "Gestión de proyectos",
    "Marketing"
  ]
}

###
POST {{host}}/experience
Content-Type: application/json

{
  
   "title": "Senior Sales Representative",
  "company": "Cardiva2",
  "startDate": "2016-03-01",
  "finishDate": "2020-01-31",
  "contract": "Indefinido",
  "description": "Representante de ventas zona norte y técnico de
quirófano en neuromodulation medical devices para el Párkinson y dolor crónico.",
  "tools": [
    "Quirófano",
    "Ventas",
    "Dolor crónico",
    "Párkinson",
    "Formador",
    "Licitaciones",
    "negociación",
    "medical devices"
  ]
}
###
POST {{host}}/experience
Content-Type: application/json

{
  "title": "Gerente y coach",
  "company": "Padelmania Romania",
  "startDate": "2015-06-01",
  "finishDate":  "2015-12-31",
  "contract": "temporada",
  "description": "Aventura en Bucharest para ayudar con la gestión y
expansión del primer club de padel de Rumania.",
  "tools": [
    "Deporte",
    "Monitor",
    "Padel",
    "Marketing"
  ]
}


###
POST {{host}}/experience
Content-Type: application/json

{
  
  "title": "Administrador de redes y ventas",
  "company": "Xtratelecom",
  "startDate": "2006-06-01",
  "finishDate": "2010-02-10",
  "contract": "Indefinido",
  "description": "Empezando por el departamento de IT administrando
redes, gestionando portabilidades y NOC y terminando en
ventas.",
  "tools": [
    "CCNA",
    "CCNP",
    "REDES",
    "Portabilidades",
    "Hacking ético"
  ]
}

###
POST {{host}}/experience
Content-Type: application/json

{
  
  "title": "Varios",
  "company": "THE ADMIRABLE CRICHTON(LONDRES),
CARAT, CORTE INGLÉS, REAL MADRID",
  "startDate": "2003-02-01",
  "finishDate": "2006-06-09",
  "contract": "Indefinido",
  "description": "Primeros pasos en el mundo laboral mientras
estudiaba haciendo venta al público, eventos,
trabajos de catering en londres y servicios generales.",
  "tools": [
    "SSGG",
    "Inglés",
    "Catering y restauración",
    "Ventas",
    "Atención al público"
  ]
}


###

GET {{host}}/studies

###
GET {{host}}/studies/1

###
POST {{host}}/studies
Content-Type: application/json

{
  "title": "Desarrollo web Fullstack",
  "school": "IDBootcamps",
  "startDate":  "2024-09-01",
  "finishDate": "2024-12-01"
  
}

###
POST {{host}}/studies
Content-Type: application/json

{
  
  "title": "Certificación Quirófano Bioingeniería",
  "school": "St.Jude Medical",
  "startDate": "2016-03-01",
  "finishDate":"2018-09-01"
  }
  

###
POST {{host}}/studies
Content-Type: application/json

{
  "title": "Ingeniería técnica informática de sistemas",
  "school": "UNED",
  "startDate": "2005-10-01"
  ,
  "finishDate": "2009-06-01"
  }
  
###
POST {{host}}/studies
Content-Type: application/json

{
  "title": "Monitos Nacional Padel",
  "school": "Federación Española de Padel",
  "startDate": "2006-03-01"
  ,
  "finishDate": "2006-04-01"
  }
###

GET {{host}}/projects

###

GET {{host}}/projects/1

###
POST {{host}}/projects
Content-Type: application/json

{
  "title": "Stimrouter",
  "description": "Rodaje, edición, diseño y márketing sobre un dispositivo médico para el dolor crónico.",
  "type": "Marketing y producción",
  "startDate": "2021-02-01",
  "finishDate": "2021-03-20",
  "technologies": [],
  "longDescription": "Implante y explicación de la mano del Dr. Daniel Camporro la implantación del sistema periférico Stimrouter mediante técnica quirúrgica abierta. Después de la presentación del caso y la cirugía, tenemos la posibilidad de visualizar una entrevista con el paciente.",
  "tools": [
    "Vegas Pro",
    "Photoshop",
    "Illustrator"
  ],
  "images": [
    "Stimrouter.png",
   
  ],
  "links": [
    "https://www.youtube.com/watch?v=a6zPuy3Dg20"
  ]
}

###
POST {{host}}/projects
Content-Type: application/json

{

  "title": "TX360",
  "description": "Coordinación, edición, diseño y márketing en Webinar sobre un dispositivo médico para el dolor crónico.",
  "type": "Diseño",
  "startDate":  "2020-04-01",
  "finishDate":  "2020-05-30",
  "technologies": [],
  "longDescription": "Webinar TX360 
Targetting SPG Del bloqueo a la neuromodulación
 Webinar sobre el funcionamiento del dispositivo TX360 para el bloque del ganglio esfenopalatino.
Se hablará tanto del diseño del dispositivo como así de la literatura clínica y las indicaciones por parte del Dr. Xia, anestesiólogo y CEO de Tian Medical, y por otro lado, el Dr. Sánchez, neurólogo del Hospital Universitario Central de Asturias, nos hablará de su experiencia con la técnica y los resultados.

La Webinar será moderada por el Prof. Láinez Andrés, jefe de servicio del Hospital Clínico Universitario y presidente de la sociedad Española de Neurología.",
  "tools": [
    "vegas pro",
    "Photoshop",
    "Illustrator",
    "youtube",
    "webinar"
  ],
  "images": [
    "tx360.png"
  ],
  "links": [
    "https://www.youtube.com/watch?v=j4Xame_dhY4"
  ]
}
###
POST {{host}}/projects
Content-Type: application/json

{
  "title": "Dolor crónico en el Covid19",
  "description": "Coordinación, edición, diseño y márketing en Webinar sobre un dispositivo médico para el dolor crónico.",
  "type": "Desarrollo",
  "startDate": "2020-04-01",
  "finishDate": "2020-06-03",
  "technologies": [
    "vegas pro",
    "Photoshop",
    "Illustrator",
    "youtube",
    "webinar"
  ],
  "longDescription": "Webinar Nueva fase 2.0 Combatir el dolor crónico 
Foro nuevos escenarios en intervencionismo

Foro debate sobre los nuevos escenarios que acontecen en la era Covid-19 en las unidades del dolor, especialmente en intervencionismo.

Gracias a los ponentes Dr. David Abejón y al Dr. José Manuel Trinidad y con la ayuda del Dr. Manuel Herrero como moderador, podremos ver los puntos más importantes tanto en el área privada como en la pública.",
  "tools": [
    "Visual Studio Code"
  ],
  "images": [
    "webinar150.png"
  ],
  "links": [
    "https://www.youtube.com/watch?v=D0C2PR1Yrwg
  ]
}